### ISSUE TITLE
hard to recover from exceptions thrown during init-key

### ISSUE THREAD

**Issue by hagmonk** [weavejester/integrant#15]
I'm refactoring my app to use integrant instead of mount. So far it's awesome, exactly what I needed. My app starts an Apache Ignite cluster and associated services, so there is a lot of state flying around, and this is by far the most elegant way of handling it that I've discovered.

One problem I have is that if any `init-key` methods throw an exception, it causes the entire value returned by `init` to be nil. This makes it hard to gracefully shut down. I actually have two integrant systems starting at different times in my app. If something fails, I need to get a handle on the existing services to tear them down, otherwise my app can hang on shutdown and cause problems in the cluster.

I propose integrant capture the exception thrown by `init-key` (which it must already be doing) and substitute that for the value that would have otherwise been set for the key. `halt!` would also need to be modified to skip such keys.

I realize this muddles the ability to detect a failed `init` by testing for nil, so perhaps this could be a third arity for `init` that lets the user explicitly opt in for this behavior if they require it. To simplify the detection of startup failures, perhaps the map `init` returns in this mode could include a key like `{:integrant/status :integrant/failed}`. That would be your clue to find and log the exceptions, start a shutdown, or even change something and retry.

Happy to hack on this for you, but wanted to get your thoughts before cutting a PR.

**Comment by weavejester** [comment]
Rather than treat the exception as a value, a better solution would be to wrap the exception with `ex-info`, similar to Component. See issue #11.

I've got some time today so I'll deal with exception handling and fix the composite keys bug as well.

**Comment by weavejester** [comment]
Should be fixed by e80fbf0. If you get an exception you can query it for the partially-built system:

```clojure
(try
  (ig/init config)
  (catch clojure.lang.ExceptionInfo ex
    (ig/halt! (:system (ex-data ex)))
    (throw (.getCause ex))))
```

I'll cut a release soon, once I've finished with a couple of other details.

**Comment by hagmonk** [comment]
Thanks very much for the rapid turnaround! I like the ex-info solution, I should use that in my own code ...

**Comment by weavejester** [comment]
The ex-info solution was shamelessly cribbed from Component ;)

**Comment by vspinu** [comment]
Any reason not to implement automatic halt-unroll on failures as part of integrant?

**Comment by NoahTheDuke** [comment]
This isn't noted anywhere in the readme, so may I suggest adding it? Would be helpful to future users.
