### ISSUE TITLE
`ig/halt!` halting not initialized keys ?

### ISSUE THREAD

**Issue by dvlopt** [weavejester/integrant#36]
I like very much the fact we can provide keys to `ig/init`. When in dev, it is useful to be able to work only with a few keys at a time. Nonetheless, it looks like dependent keys (children) of initialized dependencies (parents) are always halted when calling `ig/halt!`, even if those dependent keys have not been initialized in the first place.

If ::b needs ::a and I only init ::a, ::b will be later halted as well.

Here is a simple [gist](https://gist.github.com/dvlopt/565cbd297bc3b78665a9c29e8d9f6d32)  showing that behavior.

Is it on purpose ? If so, I can't understand why as I find it very inconvenient for my use cases.

**Comment by weavejester** [comment]
It shouldn't do. I actually ran into this bug myself yesterday and I'm working on a fix.
