### ISSUE TITLE
halt-missing-keys does not do take dependencies into account

### ISSUE THREAD

**Issue by plexus** [weavejester/integrant#40]
This may be by design, or I may be misunderstanding something, but this behavior seemed pretty counterintuitive, so I figured I'd bring it up.

We have a single "root" key that expands to cover all needed keys, so we start the system like this

``` clojure
(ig/init config [:com.nextjournal/nextjournal])
```

When doing suspend/resume we do this

``` clojure
(ig/suspend! system)
(ig/resume new-config system [:com.nextjournal/nextjournal])
```

This however calls `halt-key!` for `(remove #{:com.nextjournal/nextjournal} (keys system))`, in other words it halts everything but the root, before resuming, so suspend/resume effectively becomes halt!/init, except for this one key.

We can't do this

``` clojure
(ig/resume new-config system)
```

because there are keys in there that should not be started. 

This could be solved by having `suspend!` call `dependent-keys` before computing `missing-keys`. We will probably do this ourselves as a workaround, even though `dependent-keys` is private.

``` clojure
(ig/resume new-config system (#'ig/dependent-keys new-config [:com.nextjournal/nextjournal]))
```

Do you agree that this is an issue? Would you accept a patch for this?

**Comment by weavejester** [comment]
> This could be solved by having `suspend!` call `dependent-keys` before computing `missing-keys`. 

You mean `resume` instead of `suspend!` here?

> Do you agree that this is an issue? Would you accept a patch for this?

If I've understood you, correctly: yes and yes. `resume` should take into account dependencies in `halt-missing-keys!`.

**Comment by plexus** [comment]
> You mean resume instead of suspend! here?

Yes!

> If I've understood you correctly: yes and yes. resume should take into account dependencies in halt-missing-keys!.

I'll try to submit a PR.
