### ISSUE TITLE
Reader tag not defined although ig/ref exists

### ISSUE THREAD

**Issue by colliderwriter** [weavejester/integrant#51]
Using 0.7.0 in the REPL,
```
test.core> (ig/ref :help)
#integrant.core.Ref{:key :help}
test.core> #ig/ref :help
Syntax error reading source at (REPL:116:1).
No reader function for tag ig/ref
```
This is my first attempt to use refs so I don't have too much more to offer. The readme examples didn't work so I poked at it this far and filed.

**Comment by weavejester** [comment]
The reader tag is just for reading configurations from edn, which the README explains at the beginning:

> Alternatively, you can specify your configuration as pure edn:
>
> ```clojure
> {:adapter/jetty {:port 8080, :handler #ig/ref :handler/greet}
>  :handler/greet {:name "Alice"}}
> ```
>
> And load it with Integrant's version of read-string:
>
> ```clojure
> (def config
>  (ig/read-string (slurp "config.edn")))
> ```

**Comment by colliderwriter** [comment]
For all future searchers: the reader tag *only* works when using ig/read-string, usually in the context of reading from a file. In code, call ig/ref normally.

This does not work:
```
(def config {:handler/greet {:name #ig/ref :const.name/alice}
              :const.name/alice {:name "Alice"}
              :const.name/bob   {:name "Bob"}})
```

This works:
```
(def config2-as-string "{:handler/greet  {:name #ig/ref :const.name/alice}
              :const.name/alice {:name \"Alice\"}
              :const.name/bob   {:name \"Bob\"}}")

(def config2 (ig/read-string config2-as-string))
```

And this works:
```
(def config3 {:handler/greet {:name (ig/ref :const.name/alice)}
              :const.name/alice {:name "Alice"}
              :const.name/bob   {:name "Bob"}})
```
