### ISSUE TITLE
refsets for composite keys

### ISSUE THREAD

**Issue by RickMoynihan** [weavejester/integrant#55]
Might it be worth adding support for refsets to composite keys?

**Comment by weavejester** [comment]
Sorry, I don't understand. In what way are refsets for composite keys not already supported?

**Comment by RickMoynihan** [comment]
Well I tried and it didn't seem to work, and I only see it documented anywhere.  Though I realise now that my issue is pretty ambiguous.  Essentially I'd like an `ig/refset` to return all instances of the key they compose; without having to derive sub-keys.

e.g. semantically something like:

```
{[:app/component :instance/one] {}
  [:app/component :instance/two] {}

  :app/components {:components #ig/refset :app/component}
}
```

**Comment by weavejester** [comment]
It should work. I just tested it right now:

```clojure
user=> (require '[integrant.core :as ig])
nil

user=> (defmethod ig/init-key :app/component [_ v] v)
#object[clojure.lang.MultiFn 0x3792163 "clojure.lang.MultiFn@3792163"]

user=> (defmethod ig/init-key :app/components [_ v] v)
#object[clojure.lang.MultiFn 0x3792163 "clojure.lang.MultiFn@3792163"]

user=> (ig/init {[:app/component :instance/one] {:inst 1}
                 [:app/component :instance/two] {:inst 2}
                 :app/components {:components (ig/refset :app/component)}})

{[:app/component :instance/one] {:inst 1}
 [:app/component :instance/two] {:inst 2}
 :app/components                {:components #{{:inst 1} {:inst 2}}}}
```

**Comment by RickMoynihan** [comment]
Ahh many thanks, I can confirm this does indeed work.  

It looks like when I tried I'd mistyped and used a non-namespaced keyword as the instance key.
