### ISSUE TITLE
Consider removing pom.xml from gitignore

### ISSUE THREAD

**Issue by rschmukler** [weavejester/integrant#61]
Some build tools (`tools.deps`) need a `pom.xml` manifest to work from a Git URL. By ignoring it, people using `tools.deps` are unable to run from an unpublished branch.

**Comment by weavejester** [comment]
A `deps.edn` file would also work, right? I'd rather not commit a generated file if I can help it.

**Comment by WhittlesJr** [comment]
+1 for `deps.edn`

I always appreciate it when maintainers include these.

**Comment by rschmukler** [comment]
Yep, a `deps.edn` file would be even better!

**Comment by weavejester** [comment]
Fixed by #62.
