### ISSUE TITLE
RefMap or resolve as protocol method

### ISSUE THREAD

**Issue by clyfe** [weavejester/integrant#63]
`RefMap` would be like `RefSet` but would resolve to a map `{k -> ref}` instead a refs set. Knowing the key can be useful (think handler registration).
Alternatively, extend the `RefLike` protocol with a `resolve` method and in `expand-key` postwalk the config via it, this would allow custom `RefThing`s. Sample:

```clojure
(defprotocol RefLike
  (ref-key [r] "Return the key of the reference.")
  (resolve [r config]))
;; ...
(defn- expand-key [config value]
  (walk/postwalk
   #(cond
      (reflike? %) (resolve % config)
      :else %)
   value))
```

**Comment by clyfe** [comment]
I just noticed the `resolve-key` multi-method in 0.8.0-alpha, which can be used to bring the key into the output; nevertheless, the notes above are still desirable to have.

**Comment by clyfe** [comment]
PR https://github.com/weavejester/integrant/pull/64

**Comment by weavejester** [comment]
> Knowing the key can be useful (think handler registration).

Can you explain your use-case further?

**Comment by clyfe** [comment]
In the config map I want to have:
- a bunch of event handlers
- that handle events with the same name as the key they are mapped under
- collect them via refmap and register them in the event reactor

Outcome in the system map:
- handler under key `:k` handles events named `:k`
- under key `:k` I have the handler fn and not some complication like `{:ev :k :fn h}`

Something along these lines:

```clojure
;; ns registry
(derive ::handler :module/const)

(defn register [[k v]]
  #_(... register v to handle events named k))

(defmethod ::handlers [_ handlers]
  (run! register handlers)
  handlers)

;; ns my.handlers
(defn foo ...)
(defn bar ...)

(derive ::foo ::registry/handler)
(derive ::bar ::registry/handler)

(def config {::foo foo
             ::bar bar
             ::registry/handlers (ig/refmap ::registry/handler)})
```

**Comment by clyfe** [comment]
RefLike protocol was extended. RefMap construct was not accepted into the core.
Standalone RefMap implementation based on the extended RefLike protocol is here: https://github.com/tape-framework/refmap
