### ISSUE TITLE
ClojureScript read config.edn parity via macros

### ISSUE THREAD

**Issue by clyfe** [weavejester/integrant#66]
I believe we can introduce cljs feature parity with some of the fns that are currently clj-only (basically `read-string` & `load-namespaces`) by means of macros, at least to some extent. Example:

```
foo (a clojurescript project)
├── resources
│   └── foo
│       └── config.edn
└── src
    └── foo
        ├── core.clj
        └── core.cljs
```

```edn
;;; resources/foo/config.edn
{:foo/bar "42"
 :foo/baz #ig/ref :foo/bar}
```

```clojure
;;; src/foo/core.clj
(defmacro read-config [path]
  (-> path io/resource slurp ig/read-string))
```

```cljs
;;; src/foo/core.cljs
(def config (read-config "foo/config.edn"))
;; {:foo/bar "42"
;;  :foo/baz #integrant.core.Ref{:key :foo/bar}}
```

If this seems desirable I can make a more concrete proposal and PR.

**Comment by weavejester** [comment]
Thanks for the interesting suggestion. I'm a little leery about having `read-config` be a macro, but less wary about `load-namespaces`. I'll give it some thought.

**Comment by clyfe** [comment]
How about we have them as macros only in cljs? Options imho are:
a) Not have them in cljs.
b) Have them as macros in cljs.

**Comment by weavejester** [comment]
`read-config` could be a function if the backend was nodejs, I believe.
