### ISSUE TITLE
Donation box link?

### ISSUE THREAD

**Issue by spacegangster** [weavejester/integrant#67]
Hello James and dear contributors,

I'd like to show my support to this and other important work that you did/do in a form of monthly donations. I'm naively hoping that this would allow you to devote more time to them. If you accept such things – maybe add a Patreon link or do a github own thing?

And thanks for some of the awesomest stuff out there!

Kind regards,
Ivan

**Comment by weavejester** [comment]
Thank you for wanting a way of donating. The thought is very much appreciated.

However, I don't think there's enough left to do on Integrant to warrant a donation box. There are a few more things I'd like to add, but the design and majority of the code are unlikely to change much further.

**Comment by spacegangster** [comment]
@weavejester I'd gladly subscribe to any kind of James Reeves foundation / Patreon if such a thing would appear, as I've been enjoying your stuff [primarily Ring] for years, and if there's any chance to see more of it, I'd like to augment such a chance :)
