### ISSUE TITLE
Access to Enter Integrant presentation

### ISSUE THREAD

**Issue by jamesnyika** [weavejester/integrant#69]
Hi @weavejester 
Looking forward to learning this microframework and duct but I need (and hopefully others too) as much documentation as possible on understanding it. 

 Do you have a new location to the Enter Integrant presentation ? or can you make it part of this repo ? 

 thanks
James (yes.. another one)

**Comment by weavejester** [comment]
I have the slides but not the video of the presentation. That was done and hosted by Skillsmatter, who went into administration at the end of last year. I do plan on making a new presentation this year, however.

**Comment by jamesnyika** [comment]
Thanks @weavejester ! I am basically trying to find as much documentation that can me understand how to work with duct. I have seen comments about people requesting documentation and I am wondering if you have any ongoing activity to better document duct or of you are depending on someone out there to do it. It really is the only framework out there that seems to be light enough without being opinionated and can be better adopted if more people could understand it. Either way, as I learn it I will try and write up my learnings and share them...
