### ISSUE TITLE
Initialisation Order

### ISSUE THREAD

**Issue by d-t-w** [weavejester/integrant#74]
Would you consider an optional initialisation order, or expose the comparator that sorts system initialisation?

I find myself occasionally enforcing an order between unrelated subsystems using a key that is clearly not intended as a functional dependency, e.g.

````clojure
:license   {}
:server    {:db/connection #ig/ref :jdbc/connection
            :_ #ig/ref :license}
````

In the example above :license and :server are unrelated, but I require :license to evaluate first.

**Comment by weavejester** [comment]
Why do you require `:license` to evaluate before `:server`? What does it do?

Also, do you know about `prep-key` and `resolve-key`?

**Comment by d-t-w** [comment]
My example is slightly contrived, but lets say I want the license state to evaluate first as it may cause the system initialisation to stop and I want to ensure the server (or other, possibly side-effecting sub-system) has not started prior.

prep-key and resolve-key relate to a single key, I'm interested in controlling the initialisation order of otherwise unrelated sub-parts of a system.

**Comment by weavejester** [comment]
It sounds like you still have a dependency between `:license` and `:server`, but you're not interested in the data, just whether or not the initialization was valid.

You can set up automatic relations with `prep-key`. For example:

```clojure
(defmethod ig/prep-key :app/server [_ opts]
  (assoc opts ::depends-on (ig/ref :app/license)))
```

You can use `ig/refset` to make it an optional dependency:

```clojure
(defmethod ig/prep-key :app/server [_ opts]
  (assoc opts ::depends-on (ig/refset :app/license)))
```

**Comment by d-t-w** [comment]
Thanks James, I'm struggling to remember the usual cases but I expect generally there's an external, stateful, co-dependency where I'm not interested in the data but do require a creation order.

I'll give prep-key and/or refset a go, seems like that will work.

**Comment by dimovich** [comment]
Interesting discussion. I usually tend to prefer the config approach as in @d-t-w 's initial message, so if you have to change the init order you don't have to change the code, but only the config.
