### ISSUE TITLE
No method in multimethod 'init-key' for dispatch value

### ISSUE THREAD

**Issue by lensgolda** [weavejester/integrant#98]
Hi James, a bit confused about i'm open this issue, have tried to play with keys and namespaces, but nothing happened, so i don't understand what i'm doing wrong. Can you help please.
(maybe something with namepaces and keys)

Have an issue with no method while dispatching value
```
Execution error (IllegalArgumentException) at integrant.core/try-build-action (core.cljc:294).
No method in multimethod 'init-key' for dispatch value: :family.bot.providers.weather/weather-api-com
```
I've found same issue in duct, but looks like not my case, because haven't used any tool, plugins, config merges, only plain config edn with aero/read-config, and extending 'ig/ref for aero)
Everything works fine from repl, and issue happens only for uberjar or when running with deps cli -main method like so
 
`clj -M -m family.bot.core` or `java -cp target/family-bot-standalone.jar clojure.main -m family.bot.core`

project.clj
```
:main ^{:skip-aot true} family.bot.core
:profiles {:uberjar {:aot :all}}
```

config.edn
```clojure
{:family.bot.services.scheduling/weather       {:provider  #ig/ref :family.bot.providers.weather/weather-api-com
 :family.bot.providers.weather/weather-api-com {:key      #env WEATHER_API_KEY
                                                :base-url "http://api.weatherapi.com/v1/forecast.json?q=London&aqi=no"}}
```
namespace
```clojure
(ns family.bot.providers.weather.weather-api-com
...
(defmethod ig/init-key :family.bot.providers.weather/weather-api-com
  [_ config]
  (map->WeatherApiCom config))
```

main ns
```clojure
(ns family.bot.core
  (:require [integrant.core :as ig]
            [aero.core :as aero])
  (:gen-class))

(defmethod aero/reader 'ig/ref
  [_ _ value]
  (ig/ref value))

(defn -main
  [& args]
  (let [config (aero/read-config "config/config.edn")]
    (ig/init
      config
      [:family.bot.services.scheduling/weather])))
```

All code can be found [here](https://github.com/lensgolda/family-bot)

**Comment by weavejester** [comment]
There's nothing in your code that loads the `family.bot.providers.weather.weather-api-com` namespace. You want to either use [load-namespaces](https://github.com/weavejester/integrant#loading-namespaces) or require the namespace manually.
